# Generated by Django 4.2.1 on 2023-06-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesmineraux', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Pierre',
        ),
    ]
