# Generated by Django 4.2.1 on 2023-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesmineraux', '0002_rename_livre_pierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_livre', models.CharField(max_length=100)),
                ('contenu_pierre', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('resume', models.CharField(max_length=500)),
            ],
        ),
    ]
