# Generated by Django 4.2.1 on 2023-06-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesmineraux', '0003_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pierre',
            name='livre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mesmineraux.livre'),
        ),
    ]
