# Generated by Django 4.2.1 on 2023-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesmineraux', '0004_pierre_livre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pierre',
            new_name='mesmineraux',
        ),
    ]
