# Generated by Django 4.2.1 on 2023-06-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesmineraux', '0005_rename_pierre_mesmineraux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesmineraux',
            name='livre',
        ),
        migrations.AddField(
            model_name='livre',
            name='mesmineraux',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mesmineraux.mesmineraux'),
        ),
    ]
